# Generated by Django 6.1.1 on 2026-09-07 08:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaExito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(max_length=100)),
                ('edad_cuando_empezo', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='historias/')),
                ('historia_corta', models.TextField(max_length=300)),
                ('historia_completa', models.TextField()),
                ('proyecto_famoso', models.CharField(max_length=200)),
                ('frase_celebre', models.TextField(max_length=200)),
                ('enlace', models.URLField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insignia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(max_length=50)),
                ('condicion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('respondido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('principiante', '🌟 Principiante'), ('juegos', '🎮 Juegos'), ('webs', '🌐 Webs'), ('apps', '📱 Apps'), ('robots', '🤖 Robots')], max_length=20)),
                ('enlace', models.URLField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recursos/')),
                ('recomendado_para', models.CharField(blank=True, choices=[('creativo', '🎨 Creativo'), ('logico', '🧠 Lógico'), ('visual', '👁️ Visual'), ('social', '🤝 Social'), ('explorador', '🌍 Explorador')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('cupos', models.IntegerField()),
                ('grado_requerido', models.CharField(blank=True, choices=[('10mo', '10mo Grado'), ('11ro', '11ro Grado'), ('12mo', '12mo Grado')], max_length=10, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('inscritos', models.ManyToManyField(blank=True, related_name='eventos_inscritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(choices=[('10mo', '10mo Grado'), ('11ro', '11ro Grado'), ('12mo', '12mo Grado')], max_length=10)),
                ('edad', models.IntegerField(validators=[django.core.validators.MinValueValidator(14), django.core.validators.MaxValueValidator(19)])),
                ('nivel_programacion', models.CharField(choices=[('nunca', 'Nunca he programado'), ('un_poco', 'He programado un poco'), ('ya_se', 'Ya sé algo de programación')], default='nunca', max_length=20)),
                ('intereses', models.JSONField(default=list)),
                ('tipo_programador', models.CharField(blank=True, choices=[('creativo', '🎨 Creativo'), ('logico', '🧠 Lógico'), ('visual', '👁️ Visual'), ('social', '🤝 Social'), ('explorador', '🌍 Explorador')], max_length=20, null=True)),
                ('racha_dias', models.IntegerField(default=0)),
                ('xp_total', models.IntegerField(default=0)),
                ('nivel', models.IntegerField(default=1)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ultima_visita', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion_corta', models.TextField(max_length=300)),
                ('descripcion_completa', models.TextField()),
                ('dificultad', models.CharField(choices=[('facil', '⭐ Fácil'), ('medio', '⭐⭐ Medio'), ('dificil', '⭐⭐⭐ Difícil')], max_length=10)),
                ('tiempo_estimado', models.CharField(max_length=50)),
                ('herramientas_necesarias', models.TextField()),
                ('pasos', models.TextField()),
                ('imagen_resultado', models.ImageField(blank=True, null=True, upload_to='proyectos/')),
                ('video_enlace', models.URLField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('juego', '🎮 Juego'), ('web', '🌐 Web'), ('robot', '🤖 Robot'), ('app', '📱 App'), ('arte', '🎨 Arte')], max_length=20)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL)),
                ('favoritos', models.ManyToManyField(blank=True, related_name='proyectos_favoritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('aprobado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('historia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.historiaexito')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoCompletado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_completado', models.DateTimeField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'proyecto')},
            },
        ),
        migrations.AddField(
            model_name='proyecto',
            name='completado_por',
            field=models.ManyToManyField(related_name='proyectos_completados', through='core.ProyectoCompletado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProyectoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='proyectos_estudiantes/')),
                ('grado_estudiante', models.CharField(choices=[('10mo', '10mo Grado'), ('11ro', '11ro Grado'), ('12mo', '12mo Grado')], max_length=10)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InsigniaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desbloqueo', models.DateTimeField(auto_now_add=True)),
                ('insignia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insignia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insignias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'insignia')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_programador', models.CharField(choices=[('creativo', '🎨 Creativo'), ('logico', '🧠 Lógico'), ('visual', '👁️ Visual'), ('social', '🤝 Social'), ('explorador', '🌍 Explorador')], max_length=20)),
                ('fecha_realizado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_test', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'tipo_programador')},
            },
        ),
    ]
