# Generated by Django 6.1.1 on 2026-09-10 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_desafio_desafiocompletado_desafio_completado_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=models.CharField(choices=[('activo', '✅ Activo'), ('advertido', '⚠️ Advertido'), ('silenciado', '🔇 Silenciado'), ('suspendido', '⏸️ Suspendido'), ('baneado', '🚫 Baneado')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_fin_sancion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='fecha_sancion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='motivo_sancion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='sancionado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanciones_aplicadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
