# Generated by Django 6.1.1 on 2026-09-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_perfil_bio_perfil_seguidores_proyecto_vistas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoestudiante',
            name='archivo',
            field=models.FileField(blank=True, help_text='Sube tu proyecto terminado (ZIP, PDF, código, etc.)', null=True, upload_to='proyectos_archivos/'),
        ),
        migrations.AddField(
            model_name='proyectoestudiante',
            name='categoria',
            field=models.CharField(choices=[('juego', '🎮 Juego'), ('web', '🌐 Web'), ('robot', '🤖 Robot'), ('app', '📱 App'), ('arte', '🎨 Arte'), ('otro', '📦 Otro')], default='otro', max_length=20),
        ),
        migrations.AddField(
            model_name='proyectoestudiante',
            name='descargas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proyectoestudiante',
            name='descripcion_larga',
            field=models.TextField(blank=True, help_text='Explica cómo lo hiciste', null=True),
        ),
        migrations.AddField(
            model_name='proyectoestudiante',
            name='enlace_externo',
            field=models.URLField(blank=True, help_text='Enlace a GitHub, YouTube, etc. (opcional)', null=True),
        ),
        migrations.AddField(
            model_name='proyectoestudiante',
            name='herramientas',
            field=models.CharField(blank=True, help_text='Ej: Scratch, Python, HTML/CSS', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyectoestudiante',
            name='vistas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('comentario', '💬 Nuevo comentario'), ('aprobacion', '✅ Aprobación'), ('insignia', '🏅 Nueva insignia'), ('seguidor', '👥 Nuevo seguidor'), ('desafio', '🎯 Desafío completado'), ('sancion', '⚠️ Sanción'), ('mensaje', '✉️ Mensaje privado'), ('like', '❤️ Nuevo like'), ('descarga', '📥 Nueva descarga')], max_length=20),
        ),
        migrations.AlterField(
            model_name='proyectoestudiante',
            name='imagen',
            field=models.ImageField(help_text='Imagen de portada', upload_to='proyectos_estudiantes/'),
        ),
    ]
