# Generated by Django 6.1.1 on 2026-09-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tokenconfirmacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email_confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proyectoestudiante',
            name='archivo',
            field=models.FileField(blank=True, help_text='Sube tu proyecto terminado', null=True, upload_to='proyectos_archivos/'),
        ),
        migrations.AlterField(
            model_name='proyectoestudiante',
            name='enlace_externo',
            field=models.URLField(blank=True, help_text='Enlace a GitHub, YouTube, etc.', null=True),
        ),
    ]
